### ISSUE TITLE
Support parsing views

### ISSUE THREAD

**Issue by wmartins** [loancrate/prisma-schema-parser#2]
Hi! My team and I came across your repo when researching a way to parse/process a Prisma schema. Thank you so much for the work you did with this tool, we've been using it and it worked like a charm for us!

We're facing one issue right now that happened after we added support to [views](https://www.prisma.io/docs/concepts/components/prisma-schema/views) in our schema:

```
peg$SyntaxError: Expected "//", "///", "datasource", "enum", "generator", "model", "type", any whitespace, or end of input but "v" found.
```

This probably happens because the existing grammar doesn't recognize `view`s.

Is it in your plans to support parsing views in the near future?

Thank you!

**Comment by wmartins** [comment]
I also started drafting a thing which should take care of adding `view` to the list of recognized keywords, the same way is done for `model` and `type`. Leaving the diff here in case you want to take a look:

https://github.com/loancrate/prisma-schema-parser/compare/master...wmartins:prisma-schema-parser:feat/add-support-for-parsing-views?expand=1

I can also open a PR with this in case you think it makes sense!

**Comment by SFlorent** [comment]
Hi ! I'm putting a +1 for this feature request.

Thank you !
